language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - hhvm
  
services:
  - memcached
 
env:
  global:
    - PLUGIN_NAME=Memcached
    - PLUGIN_PATH=Plugin/Memcached
    - REQUIRE="phpunit/phpunit:3.7.31"
    - DB=mysql
    - CAKE_VERSION=2.4
  matrix:
    - CAKE_VERSION=2.2
    - CAKE_VERSION=2.3
    - CAKE_VERSION=2.4
    - CAKE_VERSION=master

matrix:
  include:
    - php: 5.4
      env:
        - COVERALLS=1
    - php: 5.4
      env:
        - PHPCS=1
    - php: 5.4
      env:
        - FOC_VALIDATE=1
        
before_script:
  - touch ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo "extension = memcached.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - git clone https://github.com/FriendsOfCake/travis.git --depth 1 ../travis
  - ../travis/before_script.sh
  - if [ "$PHPCS" != 1 ]; then
        echo "
            require_once APP . DS . 'vendor' . DS . 'phpunit' . DS . 'phpunit' . DS . 'PHPUnit' . DS . 'Autoload.php';
            CakePlugin::load('Memcached', array('bootstrap' => false, 'route' => false));
            App::uses('MemcachedEngine', '$PLUGIN_NAME.Lib/Cache/Engine');
        " >> ../cakephp/app/Config/bootstrap.php;
    fi
  
script:
  - ../travis/script.sh

after_success:
  - ../travis/after_success.sh