language: php

php:
  - 5.3
  - 5.4
  - 5.5

services:
  - memcached

env:
  - CAKE_VERSION=2.2.0 DB=mysql
  - CAKE_VERSION=2.3.0 DB=mysql
  - CAKE_VERSION=master DB=mysql
  - CAKE_VERSION=2.4 DB=mysql

before_script:
  - echo "extension = memcached.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - git clone git://github.com/cakephp/cakephp ../cakephp && cd ../cakephp && git checkout $CAKE_VERSION
  - cp -R ../CakePHP-Memcached-Engine app/Plugin/Memcached
  - chmod -R 777 ../cakephp/app/tmp
  - set +H
  - echo "

    App::uses('MemcachedEngine', 'Memcached.Lib/Cache/Engine');
    CakePlugin::loadAll();" >> ../cakephp/app/Config/bootstrap.php
  - cd app/Plugin/Memcached
  - composer self-update
  - composer install --prefer-source
  - cd ../../Console

script:
  - mkdir -p build/logs
  - ./cake test Memcached Cache/Engine/MemcachedEngine --stderr --configuration ../Plugin/Memcached/Test/phpunit.xml

after_script:
  - php ../Plugin/Memcached/vendor/bin/coveralls -v
